In [3]:
import pandas as pd
import numpy as np

In [4]:
from sklearn.datasets import load_digits

In [5]:
def write_answer(x):
    with open("answer1.txt", "w") as fout:
        fout.write(str(x))

In [6]:
digits=load_digits()

In [7]:
digits.data.shape

(1797, 64)

In [8]:
type(digits)

sklearn.utils.Bunch

In [9]:
X=digits['data']
y=digits['target']


## Decision Tree

In [39]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

clf_tree = DecisionTreeClassifier(random_state=0)

score=(cross_val_score(clf_tree, X, y, cv=10))

In [50]:
score_mean=score.mean()
score

array([0.80540541, 0.8579235 , 0.78453039, 0.80555556, 0.79888268,
       0.89385475, 0.89944134, 0.81460674, 0.8079096 , 0.83522727])

## Bagging

In [55]:
from sklearn.ensemble import BaggingClassifier
clf_bagging = BaggingClassifier(n_estimators=100, random_state=0).fit(X, y)

score_bagging=(cross_val_score(clf_bagging, X, y, cv=10))

In [56]:
score_bagging_mean=score_bagging.mean()
score_bagging

array([0.88108108, 0.96174863, 0.90607735, 0.94444444, 0.90502793,
       0.98882682, 0.95530726, 0.91011236, 0.8700565 , 0.92045455])

In [57]:
write_answer(score_bagging_mean)

## Bagging 2

In [16]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
import numpy as np
from sklearn.ensemble import BaggingClassifier
clf_bagging = BaggingClassifier(n_estimators=100, max_features=int(np.sqrt(X.shape[1])), random_state=0).fit(X, y)

score_bagging2=(cross_val_score(clf_bagging, X, y, cv=10))

In [18]:
score_bagging_mean=score_bagging2.mean()
score_bagging2

array([0.91891892, 0.96721311, 0.93370166, 0.88888889, 0.94972067,
       0.93854749, 0.97206704, 0.97752809, 0.90960452, 0.90909091])

In [19]:
write_answer(score_bagging_mean)

## Bagging3

In [20]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

clf_tree = DecisionTreeClassifier(random_state=0,max_features=int(np.sqrt(X.shape[1])))

clf_bagging = BaggingClassifier(base_estimator=clf_tree,n_estimators=100, random_state=0).fit(X, y)

score_bagging3=(cross_val_score(clf_bagging, X, y, cv=10))

In [21]:
score_bagging_mean=score_bagging3.mean()
score_bagging3

array([0.90810811, 0.96721311, 0.93922652, 0.96111111, 0.94972067,
       0.98324022, 0.98882682, 0.96629213, 0.93785311, 0.94318182])

In [22]:
write_answer(score_bagging_mean)